### PR TITLE
PIC-1033: Added key details banner on match-defendant view when comin…

### PR DESCRIPTION
**Pull request by katie-cawthorne**
…g from case-summary

- Added key details banner on match-defendant view when coming from case-summary.
- Key details banner will not display on match-defendant view when coming from `/match/bulk` as per acceptance criteria.

### CODE REVIEW

**Review by sarahyjja — APPROVED** [review]
coolio :)

**Review by theDustRoom — CHANGES_REQUESTED** [review]
We could do with some BDD around this but other than that it's noice 👍

**Comment by theDustRoom** [comment]
I've just realised that this change is in the wrong file, it should be within match-manual.njk

**Comment by katie-cawthorne** [comment]
Ok, I'll have a look

**Comment by katie-cawthorne** [comment]
I've removed the key details banner from `match-defendant.njk` and added to `match-manual.njk` (sorry got confused which page it was)
Updated the BDD tests

**Review by theDustRoom — APPROVED** [review]
LGTM 👍

**Pull request merged**
